name: 'Close stale issues and PRs'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

permissions:
  issues: write
  pull-requests: write
  actions: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 365
          days-before-close: 30
          
          stale-issue-message: 'This issue is now marked stale because it has been open over a year without activity. Remove the stale label or add a comment to reset the stale state. This issue will be closed in 30 days if no activity is detected.'
          stale-issue-label: Stale
          stale-pr-message: 'This pull request is now marked stale because it has been open over a year without activity. Remove the stale label or add a comment to reset the stale state. This pull request will be closed in 30 days if no activity is detected.'
          stale-pr-label: Stale

          close-issue-label: 'Issue Cleanup: Closed'
          close-issue-message: 'This issue has been closed because it has been stale for at least 30 days.'
          close-issue-reason: 'not_planned'
          
          close-pr-label: 'PR Cleanup: Abandoned'
          close-pr-message: 'This pull request has been closed because it has been stale for at least 30 days.'

          exempt-issue-labels: Roadmap
          exempt-pr-labels: Roadmap
          
          operations-per-run: 1000
          debug-only: false
